### ISSUE TITLE
`pio` seems to require `std` due to cargo dependency bug

### ISSUE THREAD

**Issue by anall** [rp-rs/pio-rs#1]
If I only use the `pio_proc` crate, and not the `pio` crate, I get:

```
failed to resolve: could not find `pio` in the list of imported crates
31 |       let prog = pio_proc::pio!("
   |  ________________^
32 | |         .side_set 1
33 | |         .wrap_target
…
   | |______^ could not find `pio` in the list of imported crates
```

If I do try and include the `pio` crate as well, I get:

```
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv6m-none-eabi` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `memchr`
```

**Comment by devsnek** [comment]
`pio` is `no_std`. `pio_proc` is not, because it is a proc macro, which runs at compile time. Can you provide more info about how you're using this?

**Comment by anall** [comment]
Ah, I see that `pio` _is_ `no_std`, but it pulls in `lalrpop-util` which by default is not `no_std`: you need to specify `default-features = false` to prevent that

To simplify things, just cloning this and running `cargo build --target thumbv6m-none-eabi`

… Actually, I wonder if this is a cargo bug?

With:

```
[build-dependencies]
lalrpop = { git = "https://github.com/lalrpop/lalrpop.git", rev = "a8afe7d" }
```

in the `Cargo.toml`, it seems like the features for `lalrpop-util` from the `lalrpop` build dependency get propagated to the `lalrpop-util` in dependencies.

If I comment that out, everything builds up until `build.rs` which needs `lalrpop`

**Comment by anall** [comment]
And aha: https://doc.rust-lang.org/cargo/reference/features.html#feature-resolver-version-2

If I add that, and `default-features = false` to the `lalrpop-util` dependency, I can get farther (all the dependencies compile)

And I am just left with: a bunch of `error[E0432]: unresolved import `self::__lalrpop_util::lexer`` ( probably because the `lexer` feature, which isn't no_std, was getting accidentally enabled due to the cargo issue )

**Comment by devsnek** [comment]
I'll split the parser out into a separate crate, and leave the assembler as no_std so it can be used on-device.

**Comment by anall** [comment]
Thanks.
