### ISSUE TITLE
proc-macro

### ISSUE THREAD

**Issue by LU15W1R7H** [rp-rs/pio-rs#2]
Is it possible to write a procedural macro, which takes assembly code as input and generates the corresponding pio-rs function calls, like the `@rp2.asm_pio` micropython decorator?

**Comment by devsnek** [comment]
This repo contains the `pio_proc` crate, and https://github.com/rp-rs/rp-hal/pull/9 has code which would allow you to do something like:

```rust
use pio_proc::pio;
use rp_hal::pio::PIOBuilder;

let program = pio!("
	write your pio program assembly here
");

PIOBuilder::default()
	.with_program(program)
	.build()
```

**Comment by LU15W1R7H** [comment]
Okay nice. Why is this done in `rp-hal` instead of here?
