### ISSUE TITLE
pio_proc panicked when sideset 1 

### ISSUE THREAD

**Issue by circuit4u-medium** [rp-rs/pio-rs#27]
```
let pm = pio_proc::pio_asm!(    
    "out x, 1 side 1 [2]",    
).program;

for x in &pm.code {
    println!("{:#016b}",x)    
    
}
```

proc macro panicked
help: message: 'side' set must be >=0 and <=0

On the other hand
```
let pm = pio_proc::pio_asm!(    
    "out x, 1 side 0 [2]",    
).program;

for x in &pm.code {
    println!("{:#016b}",x)    
    
}
```
gives

0b110001000100001

**Comment by jannic** [comment]
You need to reserve a number of bits for side set before using them. See this line in the example: https://github.com/rp-rs/rp-hal/blob/main/rp2040-hal/examples/pio_side_set.rs#L40

**Comment by circuit4u-medium** [comment]
Yes, my bad. 

Also I found that ".side_set 1 opt" can be useful as well, when you don't have "side" for each statement. 

(reference https://datasheets.raspberrypi.com/pico/raspberry-pi-pico-c-sdk.pdf page 37)
