### ISSUE TITLE
jmp does not respect configured .origin

### ISSUE THREAD

**Issue by nvx** [rp-rs/pio-rs#34]
The `.origin` directive allows programs to be loaded at positions other than 0 in the state machine address space. This directive is important as the `JMP` operand uses absolute addresses and not relative addresses.

Unfortunately at least the `pio_proc::pio_asm!` macro does not take this into account when generating `JMP` opcodes.

```
        let program = pio_proc::pio_asm!(
            ".origin 16",
            ":wait_clk",
            "wait 0 gpio 15",
            "wait 1 gpio 15",
            "jmp wait_clk",
        );
        defmt::info!("pio: {:x}", &program.program.code as &[u16]);
```

For example the above program compiles the jmp to `0x0000` (unconditional jump to address 0), which is what would be expected if the origin was 0. The expected behaviour would be for this to compile to `0x0010` which would be an unconditional jump to address 16.

A temporary workaround (which would break when a fix for this is implemented mind you) would be to do something like this:

```
        let program = pio_proc::pio_asm!(
            ".define origin 16",
            ".origin origin",
            ":wait_clk",
            "wait 0 gpio 15",
            "wait 1 gpio 15",
            "jmp y-- wait_clk+origin",
        );
        defmt::info!("pio: {:x}", &program.program.code as &[u16]);
```

**Comment by devsnek** [comment]
If you feel like contributing, this should be a relatively simple fix, as origins are already parsed correctly. You'd just need to feed them into the assembler.

**Comment by jannic** [comment]
Such a change would break the program loading code in rp2040-hal: `pio.install(program)` contains relocation logic which adds the program offset to all JMP instruction targets: https://github.com/rp-rs/rp-hal/blob/main/rp2040-hal/src/pio.rs#L199

This is definitely necessary if the program doesn't specify an origin and the program is loaded to some dynamically determined non-zero offset.

One can argue that a program which defines an origin should already contain JMP targets respecting that origin, and no further rewriting should occur. That's what @nvx suggests here, and it's a very reasonable suggestion. However if we apply this change to pio-rs, we should mark it as a breaking change, incrementing the version number accordingly. When updating the dependency in rp2040-hal, we need to change the loading logic to no longer rewrite programs which specify an origin.

How does the pio assembler from the C SDK handle this? We probably should do the same, to avoid confusion.

**Comment by nvx** [comment]
> Such a change would break the program loading code in rp2040-hal: `pio.install(program)` contains relocation logic which adds the program offset to all JMP instruction targets: https://github.com/rp-rs/rp-hal/blob/main/rp2040-hal/src/pio.rs#L199

I wasn't aware it did this, neat. I'm currently testing out the embassy-rp PIO PR when I ran into this issue as it doesn't do such a thing (https://github.com/embassy-rs/embassy/pull/1043)

> How does the pio assembler from the C SDK handle this? We probably should do the same, to avoid confusion.

This makes the most sense from an interoperability perspective. I haven't actually looked at what the C SDK does though.

**Comment by ithinuel** [comment]
Actually, the pico-sdk also does applies the offset to the jmp instructions, [see line 110](https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/hardware_pio/pio.c#L104-L132).

However, the pico-sdk first [finds the offset](https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/hardware_pio/pio.c#L63-L79) and if none is pre-set then it searches for first a fit from the end.

This is what [rp2040-hal does too](https://github.com/rp-rs/rp-hal/blob/4b2b33b950d06ad690cde7088db2545e39f02221/rp2040-hal/src/pio.rs#L193).
pio-rs seem to support that feature too and has [tests for it](https://github.com/rp-rs/pio-rs/blob/main/pio-parser/src/lib.rs#L413-L441).

So, when inspecting the program before it gets installed it may look like the jmp offsets are incorrect but they are (should be) actually valid once installed.

**Comment by nvx** [comment]
> So, I think that the current code's behaviour is correct and that the fix need to be in the doc with a reminder that the label's addresses are to be considered relative until the program is installed.

That seems reasonable. I'll follow up in the embassy PIO PR to get the behaviour fixed there. Thanks for your time!
