### ISSUE TITLE
Case sensitivity for pio asm

### ISSUE THREAD

**Issue by QuantumEF** [rp-rs/pio-rs#49]
It seems that the PIO assembly that is capitalize will not properly compile. 
I notices this issue when copying the [quadrature encoder example in the pico-examples repo](https://github.com/raspberrypi/pico-examples/blob/master/pio/quadrature_encoder/quadrature_encoder.pio). Only after converting everything to lowercase does it compile: my example https://github.com/QuantumEF/tcp_motor_controller/blob/main/src/quadrature_encoder.pio.

I am thinking it should be a simple fix, so I will begin looking into how to fix it. Note: I am new to the Rust language.

**Comment by devsnek** [comment]
the lexer for pioasm defines that the entire grammar is case-insensitive: https://github.com/raspberrypi/pico-sdk/blob/6a7db34ff63345a7badec79ebea3aaef1712f374/tools/pioasm/lexer.ll#L22

there's no built-in feature for this in lalrpop, so i think you'll need to manually map each token here unfortunately: https://github.com/rp-rs/pio-rs/blob/42e8c135406ea6fdea51e76076737822a73eea30/pio-parser/src/pio.lalrpop#L24

https://github.com/lalrpop/lalrpop/blob/0c3599bd79d2f29252c165a13ffd5f7a71ac4af0/doc/src/lexer_tutorial/001_lexer_gen.md?plain=1#L307-L322

**Comment by jannic** [comment]
@devsnek, do you know if that flag also affects labels? Ie. are labels case-insensitive in pioasm?

**Comment by QuantumEF** [comment]
Should be fine. I thought it would be auto closed with the merge.
