### ISSUE TITLE
pio asm fails to install

### ISSUE THREAD

**Issue by JonasFocke01** [rp-rs/pio-rs#51]
Hello,  

I have a pio asm program that fails to install with the `NoSpace` error in an empty state machine.  
The program is intended to read [DMX512](https://en.wikipedia.org/wiki/DMX512) data.  It comes from [this](https://github.com/jostlowe/Pico-DMX/blob/main/extras/DmxInput.pio) repo, where it compiles for C, but not for rust.  
Can you spot anything wrong here?  

```
.program DmxInput
.define dmx_bit 4                     ; As DMX has a baudrate of 250.000kBaud, a single bit is 4us

break_reset:
    set x, 29                         ; Setup a counter to count the iterations on break_loop

break_loop:                           ; Break loop lasts for 8us. The entire break must be minimum 30*3us = 90us
    jmp pin break_reset               ; Go back to start if pin goes high during the break
    jmp x-- break_loop   [1]          ; Decrease the counter and go back to break loop if x>0 so that the break is not done
    wait 1 pin 0                      ; Stall until line goes high for the Mark-After-Break (MAB)

.wrap_target
    wait 0 pin 0                      ; Stall until start bit is asserted
    set x, 7             [dmx_bit]    ; Preload bit counter, then delay until halfway through

bitloop:
    in pins, 1                        ; Shift data bit into ISR
    jmp x-- bitloop      [dmx_bit-2]  ; Loop 8 times, each loop iteration is 4us
    wait 1 pin 0                      ; Wait for pin to go high for stop bits
    in null, 24                       ; Push 24 more bits into the ISR so that our one byte is at the position where the DMA expects it
    push                              ; Should probably do error checking on the stop bits some time in the future....

.wrap
```
DISCLAIMER: I tinkered with it, but i have NOT WRITTEN this program, as it comes from the mentioned repo.

**Comment by jannic** [comment]
Hi!
This program is much too short to cause a `NoSpace` error in an empty state machine. Can you show us the code you use to install the pio program?

**Comment by ithinuel** [comment]
Note, the 4 state machines share the same 32 words in a given Pio.
So if you install other programs used in othe state machines,  they'll be using some of those 32 words.

**Comment by JonasFocke01** [comment]
@ithinuel this was Precicely what was causing the error. I now use pio1 for that, and it works.  
Thank you <3
